<?php
$headerMenu = $this->headerMenu->getMenu();
?>

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                
                <?php
                $i = 0;
                $countOuter = count($headerMenu);
                while($i < $countOuter)
                {
                ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $headerMenu[$i][0]['menu']; ?> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <?php
                        $j = 0;
                        $countInner = count($headerMenu[$i]);
                        while($j < $countInner)
                        {
                        ?>
                            <li><a href="<?php echo $headerMenu[$i][$j]['route'];?>"><?php echo $headerMenu[$i][$j]['sub_menu'];?></a></li>                        
                        <?php
                        $j++;
                        }
                        ?>
                    </ul>
                </li>                        
                <?php
                $i++;
                }
                ?>
            </ul>
        </div>
    </div>
</nav>
